<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>formulario</title>
</head>
<body>
<form action="ler_dados.php">
    <label for="nome">Nome</label>
    <input type="text" name="nome" id="nome"><br>
    <label for="idade">Idade:</label>
    <input type="number" number="idade" id="idade"><br>
    <input type="submit"> 
    
</body>
</html>